service: backend-erin-scheduler
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  memorySize: 1024
  timeout: 15
  eventBridge:
    useCloudFormation: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
            - events:PutRule
            - events:PutTargets
            - lambda:InvokeFunction
          Resource: 
            - arn:aws:events:us-east-1:452999660372:event-bus/default
            - arn:aws:events:us-east-1:452999660372:rule/*
            - arn:aws:lambda:us-east-1:452999660372:function/*

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  Resources:
    RuleCreateEvent:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: default
        Name: 'erin-event' 
        EventPattern:
          source:
            - backend-erin-api
          detail-type:
            - send-email
            
    EventScheduleRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EventScheduleRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - scheduler.amazonaws.com
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEventBridgeSchedulerFullAccess
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  api:
    handler: handler.api
    destinations:
      onSuccess: arn:aws:events:us-east-1:452999660372:event-bus/default
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      MONGO_DEV: ${env:MONGO_DEV}
      MONGO_PROD: ${env:MONGO_PROD}
      SMTP_USERNAME: ${env:SMTP_USERNAME}
      SMTP_PASSWORD: ${env:SMTP_PASSWORD}

  sendEmail:
    handler: handler.mailer
    events:
      - eventBridge:
          eventBus: default
          description: sending a mail
          pattern:
            source:
              - backend-erin-api
            detail-type:
              - mailer
          