openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    sample app send mail using bull
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:5026
paths:
  /users:
    post:
      tags:
        - user
      summary: Create user
      description: Create new user
      requestBody:
        description: User description
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "405":
          description: Invalid input=
  /users/{id}:
    delete:
      tags:
        - user
      summary: Deletes user and redis
      description: Delete User
      parameters:
        - name: id
          in: path
          description: Pet id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid pet value

components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
          example: Rifqi
        last_name:
          type: string
          example: Riza Irfansyah
        birthday:
          type: string
          example: 2022-12-27
        location:
          type: string
          example: Asia/Jakarta
        type:
          type: string
          example: Birthday
    SuccessResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        status:
          type: boolean
          example: true
        message:
          type: string
          example: Success
      xml:
        name: user
